on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Swift ${{matrix.swift_version}} Build & Test
    runs-on: macos-latest
    
    strategy:
      matrix:
        swift_version: ["6.0", "5.10", "5.9"]
    
    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{matrix.swift_version}}
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
